### ISSUE TITLE
Default MathMLCanonicalizer is invalid

### ISSUE THREAD

**Issue by whury** [whury/MathMLCan#2]
`MathMLCanonicalizer.getDefaultCanonicalizer()` method creates invalid canonicalizer. During invocation of `canonicalize` method following exception is thrown:

`java.lang.IllegalArgumentException: property has wrong format
    at cz.muni.fi.mir.mathmlcanonicalization.modules.OperatorNormalizer.getPropertyMap(OperatorNormalizer.java:230)
    at cz.muni.fi.mir.mathmlcanonicalization.modules.OperatorNormalizer.unifyOperators(OperatorNormalizer.java:100)
    at cz.muni.fi.mir.mathmlcanonicalization.modules.OperatorNormalizer.execute(OperatorNormalizer.java:91)
    at cz.muni.fi.mir.mathmlcanonicalization.MathMLCanonicalizer.canonicalize(MathMLCanonicalizer.java:336)`

**Comment by whury** [comment]
`MathMLCanonicalizer.getDefaultCanonicalizer()` now uses only default-config.xml classpath resource and `modules` property is used only in case of error. This fallback is controversial - probably it would much better to throw an exception instead of returning `MathMLCanonicalizer` with unconfigured modules.
